export const AccountConstants = {
    GET_USER_ACCOUNTS: 'GET_USER_ACCOUNTS',
    GET_USER_ACCOUNTS_SUCCESS: 'GET_USER_ACCOUNTS_SUCCESS',
    GET_USER_ACCOUNTS_ERROR: 'GET_USER_ACCOUNTS_ERROR',

    ADD_USER_ACCOUNT: 'ADD_USER_ACCOUNT',
    ADD_USER_ACCOUNT_SUCCESS: 'ADD_USER_ACCOUNT_SUCCESS',
    ADD_USER_ACCOUNT_ERROR: 'ADD_USER_ACCOUNT_ERROR',

    UPDATE_USER_ACCOUNT: 'UPDATE_USER_ACCOUNT',
    UPDATE_USER_ACCOUNT_SUCCESS: 'UPDATE_USER_ACCOUNT_SUCCESS',
    UPDATE_USER_ACCOUNT_ERROR: 'UPDATE_USER_ACCOUNT_ERROR',

    DELETE_USER_ACCOUNT: 'DELETE_USER_ACCOUNT',
    DELETE_USER_ACCOUNT_SUCCESS: 'DELETE_USER_ACCOUNT_SUCCESS',
    DELETE_USER_ACCOUNT_ERROR: 'DELETE_USER_ACCOUNT_ERROR',

    SET_FILTERS: 'SET_FILTERS',

    SHOW_ACCOUNT_FORM: 'SHOW_ACCOUNT_FORM',
    HIDE_ACCOUNT_FORM: 'HIDE_ACCOUNT_FORM',
};
