export const SystemConstants = {
    GET_SYS_SCREEN: 'GET_SYS_SCREEN',
    GET_SYS_SCREEN_SUCCESS: 'GET_SYS_SCREEN_SUCCESS',
    GET_SYS_SCREEN_ERROR: 'GET_SYS_SCREEN_ERROR',

    ADD_SYS_SCREEN: 'ADD_SYS_SCREEN',
    ADD_SYS_SCREEN_SUCCESS: 'ADD_SYS_SCREEN_SUCCESS',
    ADD_SYS_SCREEN_ERROR: 'ADD_SYS_SCREEN_ERROR',

    DELETE_SYS_SCREEN: 'DELETE_SYS_SCREEN',
    DELETE_SYS_SCREEN_SUCCESS: 'DELETE_SYS_SCREEN_SUCCESS',
    DELETE_SYS_SCREEN_ERROR: 'DELETE_SYS_SCREEN_ERROR',

    SET_FILTERS: 'SET_FILTERS',

    SHOW_ACCOUNT_FORM: 'SHOW_ACCOUNT_FORM',
    HIDE_ACCOUNT_FORM: 'HIDE_ACCOUNT_FORM',
};
